In [1]:
# import the libraries
import pandas as pd
import numpy as np
import os
import openpyxl
import datetime
from pandasgui import show

In [2]:
# importing openpyxl module
import openpyxl

# input excel file path
inputExcelFile ="MorpaData.xlsx"

# creating or loading an excel workbook
newWorkbook = openpyxl.load_workbook(inputExcelFile)

# printing all the sheetnames in an excel file using sheetnames attribute
print('The Sheet names of the given excel file: ')

# Getting the sheetnames as a list using the sheetnames attribute
sheetNames=newWorkbook.sheetnames

# Traversing in the sheetNames list
for name in sheetNames:
   print(name)

The Sheet names of the given excel file:
Üye Listesi
Giriş Logları
Oyun
Konu anlatımı
çalışmalar
Sınav
konu

In [3]:
# get the member data from excel

member_df = pd.read_excel('MorpaData.xlsx',sheet_name='Üye Listesi')
print(member_df.head(10),'\n\n')

print(member_df.info())

# get the unique number of members

print(member_df['Üye'].nunique())

       Üye  Şehir    İlçe       Okul  Sınıf
0  2070306  10826  162678  120166963      4
1  2910824  16378  624995  813905547      6
2  3045726  10989  721319  231052437      4
3  3661377  10185  376777  733057858      8
4  3794510  11631  709268   72006202      4
5  3969040  11631  626646  305454095      5
6  5084112  11631   23819  659915466      8
7  6789503  15012  248394  310622551      3
8  7221591  11631  485022  529623633      3
9  7899454  14951  599378  265076040      8


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1999 entries, 0 to 1998
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Üye     1999 non-null   int64
 1   Şehir   1999 non-null   int64
 2   İlçe    1999 non-null   int64
 3   Okul    1999 non-null   int64
 4   Sınıf   1999 non-null   int64
dtypes: int64(5)
memory usage: 78.2 KB
None
1999

In [4]:
# get the Login logs data from excel

login_df = pd.read_excel('MorpaData.xlsx',sheet_name='Giriş Logları')
login_df['Giriş Zamanı'] = pd.to_datetime(login_df['Giriş Zamanı'], format='%d/%m/%Y %H:%M:%S')
login_df['Çıkış Zamanı'] = pd.to_datetime(login_df['Çıkış Zamanı'], format='%d/%m/%Y %H:%M:%S')
print(login_df.head(10),'\n\n')

print(login_df.info(),'\n\n')


# get the unique number of members on login data
print("unique member count on login data: ",login_df['Üye'].nunique())

   GirişID      Üye            Giriş Zamanı            Çıkış Zamanı  \
0   181915  2070306 2021-09-09 20:54:37.683 2021-09-09 21:46:55.070
1   128004  2910824 2021-09-07 20:33:32.583 2021-09-07 21:25:53.753
2   178974  2910824 2021-09-09 20:18:36.960 2021-09-09 20:58:58.370
3   182887  2910824 2021-09-09 21:10:33.563 2021-09-09 22:04:55.467
4   238434  2910824 2021-09-12 10:59:55.210 2021-09-12 11:04:15.233
5   244552  2910824 2021-09-12 12:32:28.067 2021-09-12 13:28:49.353
6   273273  2910824 2021-09-13 13:25:51.117 2021-09-13 13:58:05.470
7   273943  2910824 2021-09-13 13:58:05.470 2021-09-13 14:36:48.393
8   285795  2910824 2021-09-13 18:44:16.997 2021-09-13 19:44:59.743
9   345946  2910824 2021-09-15 17:06:06.027 2021-09-15 17:51:50.893

   Süre Dakika
0           52
1           52
2           40
3           54
4            5
5           56
6           33
7           38
8           60
9           45


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21569 entries, 0 to 21568
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   GirişID       21569 non-null  int64
 1   Üye           21569 non-null  int64
 2   Giriş Zamanı  21569 non-null  datetime64[ns]
 3   Çıkış Zamanı  21569 non-null  datetime64[ns]
 4   Süre Dakika   21569 non-null  int64
dtypes: datetime64[ns](2), int64(3)
memory usage: 842.7 KB
None


unique member count on login data:  1999

In [5]:
lecturing_df = pd.read_excel('MorpaData.xlsx',sheet_name='Konu anlatımı')
lecturing_df['Giriş Zamanı'] = pd.to_datetime(lecturing_df['Giriş Zamanı'], format='%d/%m/%Y %H:%M:%S')
lecturing_df['Çıkış Zamanı'] = pd.to_datetime(lecturing_df['Çıkış Zamanı'], format='%d/%m/%Y %H:%M:%S')
print(lecturing_df.head(10),'\n\n')

print(lecturing_df.info(),'\n\n')


# get the unique number of members on lecturing data
print("unique member count on lecturing data: ",lecturing_df['Üye'].nunique())

       Üye  Eğitim Materyali  Eğitim Materyali Türü  Ders   Konu  \
0  2070306      518826088921                      2     2   9864
1  2070306      608022794749                      2     2   9864
2  2910824      633794085515                      2     2   8964
3  2910824      787304215519                      2     9   9535
4  2910824      137540475371                      2     3   9659
5  2910824      799934114128                      2    11   4421
6  2910824      139874336279                      2     1  10002
7  2910824      884070756143                      2     2   8965
8  2910824      884070756143                      2     2   8965
9  2910824      139874336279                      2     1  10002

   Katılım Oranı  Performans            Giriş Zamanı            Çıkış Zamanı  \
0             75           0 2021-09-09 20:55:06.357 2021-09-09 21:00:04.783
1            100           0 2021-09-09 21:00:04.797 2021-09-09 21:46:55.070
2             66           0 2021-09-07 20:37:27.890 2021-09-07 21:25:53.757
3             66           0 2021-09-09 21:10:49.753 2021-09-09 21:18:02.070
4             20           0 2021-09-12 12:32:43.120 2021-09-12 12:42:34.610
5             85           0 2021-09-13 18:45:26.420 2021-09-13 18:52:45.190
6             25           0 2021-09-15 17:06:56.013 2021-09-15 17:09:49.703
7             25           0 2021-09-15 17:09:49.703 2021-09-15 17:51:50.900
8             50           0 2021-09-15 18:02:41.340 2021-09-15 18:06:59.627
9             25           0 2021-09-17 18:22:05.173 2021-09-17 18:23:40.413

   GirişLog
0    181915
1    181915
2    128004
3    182887
4    244552
5    285795
6    345946
7    345946
8    349321
9    414086


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19061 entries, 0 to 19060
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Üye                    19061 non-null  int64
 1   Eğitim Materyali       19061 non-null  int64
 2   Eğitim Materyali Türü  19061 non-null  int64
 3   Ders                   19061 non-null  int64
 4   Konu                   19061 non-null  int64
 5   Katılım Oranı          19061 non-null  int64
 6   Performans             19061 non-null  int64
 7   Giriş Zamanı           19061 non-null  datetime64[ns]
 8   Çıkış Zamanı           19061 non-null  datetime64[ns]
 9   GirişLog               19061 non-null  int64
dtypes: datetime64[ns](2), int64(8)
memory usage: 1.5 MB
None


unique member count on lecturing data:  1554

In [6]:
# get the member studies data from excel

studies_df = pd.read_excel('MorpaData.xlsx',sheet_name='çalışmalar')
studies_df['Giriş Zamanı'] = studies_df['Giriş Zamanı'].apply(lambda x: x.strftime("%d/%m/%Y  %H:%M:%S"))
studies_df['Çıkış Zamanı'] = studies_df['Çıkış Zamanı'].apply(lambda x: x.strftime("%d/%m/%Y  %H:%M:%S"))
print(studies_df.head(10),'\n\n')

print(studies_df.info(),'\n\n')

# get the unique number of members on studies data
print("unique member count on studies data: ",studies_df['Üye'].nunique())

       Üye  Eğitim Materyali  Eğitim Materyali Türü  Ders   Konu  \
0  2910824      291765069973                      3     2   8964
1  2910824      383712317425                      3     9   9535
2  2910824      291765069973                      3     2   8964
3  2910824      450320146095                      3     3   9659
4  2910824      460263704270                      3    11   4421
5  2910824      170232354529                      3     2   8965
6  2910824      343498413848                      3     1  10002
7  2910824      924340585642                      3     2   8966
8  2910824      990590760357                      3     3   9661
9  2910824       90390416811                      3     2   8971

   Katılım Oranı  Performans          Giriş Zamanı          Çıkış Zamanı  \
0            100          62  07/09/2021  20:34:09  07/09/2021  20:37:27
1            100          90  09/09/2021  21:18:02  09/09/2021  22:04:55
2             80          94  12/09/2021  11:01:47  12/09/2021  11:04:15
3            100          80  12/09/2021  12:42:34  12/09/2021  13:28:49
4            100          92  13/09/2021  18:52:45  13/09/2021  19:44:59
5            100          67  15/09/2021  18:06:59  15/09/2021  18:57:46
6            100          61  17/09/2021  18:23:46  17/09/2021  19:08:46
7             80          41  19/09/2021  12:08:04  19/09/2021  12:53:47
8            100          64  20/09/2021  20:01:59  20/09/2021  20:02:39
9            100          80  22/09/2021  20:44:35  22/09/2021  20:46:36

   GirişLog
0    128004
1    182887
2    238434
3    244552
4    285795
5    349321
6    414086
7    463111
8    519306
9    598986


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10965 entries, 0 to 10964
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Üye                    10965 non-null  int64
 1   Eğitim Materyali       10965 non-null  int64
 2   Eğitim Materyali Türü  10965 non-null  int64
 3   Ders                   10965 non-null  int64
 4   Konu                   10965 non-null  int64
 5   Katılım Oranı          10965 non-null  int64
 6   Performans             10965 non-null  int64
 7   Giriş Zamanı           10965 non-null  object
 8   Çıkış Zamanı           10965 non-null  object
 9   GirişLog               10965 non-null  int64
dtypes: int64(8), object(2)
memory usage: 856.8+ KB
None


unique member count on studies data:  1311

In [7]:
# get the member exams data from excel

exams_df = pd.read_excel('MorpaData.xlsx',sheet_name='Sınav')
exams_df['Giriş Zamanı'] = exams_df['Giriş Zamanı'].apply(lambda x: x.strftime("%d/%m/%Y  %H:%M:%S"))
exams_df['Çıkış Zamanı'] = exams_df['Çıkış Zamanı'].apply(lambda x: x.strftime("%d/%m/%Y  %H:%M:%S"))
print(exams_df.head(10),'\n\n')

print(exams_df.info(),'\n\n')

# get the unique number of members on exams data
print("unique member count on exams data: ",exams_df['Üye'].nunique())


# wrong answers are not deducted from the total score.

       Üye         Sınav   Konu  Sınav Türü  Doğru Sayısı  Yanlış Sayısı  \
0  2910824  268222943622   8964           1             8              1
1  2910824  501151045356   9535           1             9              0
2  2910824  934072969211   9659           1             8              2
3  2910824  934072969211   9659           1             9              1
4  2910824     438484723   4421           1             4              6
5  2910824  523324425042   8965           1             0              8
6  2910824  182157124583  10002           1             0              0
7  2910824  182157124583  10002           1             5              5
8  2910824  636098373206   8971           1             9              0
9  2910824  808509304221   9662           1             3              6

   Boş Sayısı  Puan          Giriş Zamanı          Çıkış Zamanı  Süre  \
0           1    80  07/09/2021  20:40:54  07/09/2021  20:45:06   237
1           1    90  09/09/2021  21:20:08  09/09/2021  21:24:25   241
2           0    80  12/09/2021  11:03:55  12/09/2021  12:48:24   149
3           0    90  13/09/2021  14:03:34  13/09/2021  14:14:50   659
4           0    40  13/09/2021  18:53:41  07/10/2021  19:32:12   115
5           2     0  15/09/2021  18:09:04  15/09/2021  18:17:35   492
6          10     0  17/09/2021  18:27:05  17/09/2021  18:27:30     5
7           0    50  17/09/2021  18:27:23  17/09/2021  18:28:56    73
8           1    90  22/09/2021  20:45:43  28/09/2021  19:29:37   588
9           1    30  23/09/2021  20:31:26  23/09/2021  20:34:46   176

   GirişLog
0    128004
1    182887
2    238434
3    273943
4    285795
5    349321
6    414086
7    414086
8    598986
9    639881


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8305 entries, 0 to 8304
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Üye            8305 non-null   int64
 1   Sınav          8305 non-null   int64
 2   Konu           8305 non-null   int64
 3   Sınav Türü     8305 non-null   int64
 4   Doğru Sayısı   8305 non-null   int64
 5   Yanlış Sayısı  8305 non-null   int64
 6   Boş Sayısı     8305 non-null   int64
 7   Puan           8305 non-null   int64
 8   Giriş Zamanı   8305 non-null   object
 9   Çıkış Zamanı   8305 non-null   object
 10  Süre           8305 non-null   int64
 11  GirişLog       8305 non-null   int64
dtypes: int64(10), object(2)
memory usage: 778.7+ KB
None


unique member count on exams data:  1079

In [8]:
# get the member subject data from excel

subject_df = pd.read_excel('MorpaData.xlsx',sheet_name='konu')
subject_df.head(10)

#sort according to aktif materyal sayısı

subject_df.sort_values(by=['Aktif Materyal Sayısı'],ascending=False)

      Sınıf  Ders  Konu  Aktif Materyal Sayısı  Toplam Materyal Sayısı
4499     25     2   899                     58                      58
4110     22     1  7699                     42                      49
5324     36     3  6749                     39                      39
3916     20     3  2192                     38                      39
4728     27     3  4338                     37                      37
...     ...   ...   ...                    ...                     ...
4794     28     2  4585                      0                       1
4795     28     2  4586                      0                       1
4796     28     2  4587                      0                       1
872       4     2  9870                      0                       3
4821     28     2  4627                      0                       1

[5643 rows x 5 columns]

In [9]:
#left join the exam and subject dataframes

exam_subject_df = pd.merge(exams_df,subject_df,how='left',left_on='Konu',right_on='Konu')

#make sınıf column as integer

exam_subject_df['Sınıf'] = exam_subject_df['Sınıf']
exam_subject_df['Ders'] = exam_subject_df['Ders']
exam_subject_df['Aktif Materyal Sayısı'] = exam_subject_df['Aktif Materyal Sayısı']
exam_subject_df['Toplam Materyal Sayısı'] = exam_subject_df['Toplam Materyal Sayısı']

In [10]:
#sum study time for each member on studies data for each unique member for each unique subject

# make str to timestamp

studies_df['Giriş Zamanı'] = pd.to_datetime(studies_df['Giriş Zamanı'], format='%d/%m/%Y %H:%M:%S')
studies_df['Çıkış Zamanı'] = pd.to_datetime(studies_df['Çıkış Zamanı'], format='%d/%m/%Y %H:%M:%S')

studies_df['Çalışma Süresi'] = studies_df['Çıkış Zamanı'] - studies_df['Giriş Zamanı']
studies_df['Çalışma Süresi'] = studies_df['Çalışma Süresi'].dt.total_seconds()
studies_df['Çalışma Süresi'] = studies_df['Çalışma Süresi'].astype(int)
# studies_df.head(10)

#left join the exam_subject_df and studies_df according to member and subject

exam_subject_studies_df = pd.merge(exam_subject_df,studies_df,how='left',left_on=['Üye','Konu'],right_on=['Üye','Konu'])


display(exam_subject_studies_df.head(10))
exam_subject_studies_df.to_csv('exam_subject_studies_df.csv', encoding='utf-8-sig')


#sınav saatinden önceki toplam çalışma süresi

exam_subject_studies_df['Çalışma Süresi'] = exam_subject_studies_df['Çalışma Süresi'].fillna(0)
exam_subject_studies_df['Çalışma Süresi'] = exam_subject_studies_df['Çalışma Süresi'].astype(int)
exam_subject_studies_df['Sınav Saati'] = exam_subject_studies_df['Sınav Saati'].apply(lambda x: x.strftime("%d/%m/%Y %H:%M:%S"))
exam_subject_studies_df['Sınav Saati'] = pd.to_datetime(exam_subject_studies_df['Sınav Saati'], format='%d/%m/%Y %H:%M:%S')

exam_subject_studies_df['Giriş Zamanı'] = pd.to_datetime(exam_subject_studies_df['Giriş Zamanı'], format='%d/%m/%Y %H:%M:%S')
exam_subject_studies_df['Çıkış Zamanı'] = pd.to_datetime(exam_subject_studies_df['Çıkış Zamanı'], format='%d/%m/%Y %H:%M:%S')

,Üye,Sınav,Konu,Sınav Türü,Doğru Sayısı,Yanlış Sayısı,Boş Sayısı,Puan,Giriş Zamanı_x,Çıkış Zamanı_x,...,Toplam Materyal Sayısı,Eğitim Materyali,Eğitim Materyali Türü,Ders_y,Katılım Oranı,Performans,Giriş Zamanı_y,Çıkış Zamanı_y,GirişLog_y,Çalışma Süresi
0,2910824,268222943622,8964,1,8,1,1,80,07/09/2021 20:40:54,07/09/2021 20:45:06,...,6.0,2.917651e+11,3.0,2.0,100.0,62.0,2021-09-07 20:34:09,2021-09-07 20:37:27,128004.0,198.0
1,2910824,268222943622,8964,1,8,1,1,80,07/09/2021 20:40:54,07/09/2021 20:45:06,...,6.0,2.917651e+11,3.0,2.0,80.0,94.0,2021-09-12 11:01:47,2021-09-12 11:04:15,238434.0,148.0
2,2910824,501151045356,9535,1,9,0,1,90,09/09/2021 21:20:08,09/09/2021 21:24:25,...,6.0,3.837123e+11,3.0,9.0,100.0,90.0,2021-09-09 21:18:02,2021-09-09 22:04:55,182887.0,2813.0
3,2910824,934072969211,9659,1,8,2,0,80,12/09/2021 11:03:55,12/09/2021 12:48:24,...,6.0,4.503201e+11,3.0,3.0,100.0,80.0,2021-09-12 12:42:34,2021-09-12 13:28:49,244552.0,2775.0
4,2910824,934072969211,9659,1,9,1,0,90,13/09/2021 14:03:34,13/09/2021 14:14:50,...,6.0,4.503201e+11,3.0,3.0,100.0,80.0,2021-09-12 12:42:34,2021-09-12 13:28:49,244552.0,2775.0
5,2910824,438484723,4421,1,4,6,0,40,13/09/2021 18:53:41,07/10/2021 19:32:12,...,7.0,4.602637e+11,3.0,11.0,100.0,92.0,2021-09-13 18:52:45,2021-09-13 19:44:59,285795.0,3134.0
6,2910824,523324425042,8965,1,0,8,2,0,15/09/2021 18:09:04,15/09/2021 18:17:35,...,6.0,1.702324e+11,3.0,2.0,100.0,67.0,2021-09-15 18:06:59,2021-09-15 18:57:46,349321.0,3047.0
7,2910824,182157124583,10002,1,0,0,10,0,17/09/2021 18:27:05,17/09/2021 18:27:30,...,3.0,3.434984e+11,3.0,1.0,100.0,61.0,2021-09-17 18:23:46,2021-09-17 19:08:46,414086.0,2700.0
8,2910824,182157124583,10002,1,0,0,10,0,17/09/2021 18:27:05,17/09/2021 18:27:30,...,3.0,3.434984e+11,3.0,1.0,100.0,74.0,2021-09-22 20:51:36,2021-09-22 20:54:50,598986.0,194.0
9,2910824,182157124583,10002,1,5,5,0,50,17/09/2021 18:27:23,17/09/2021 18:28:56,...,3.0,3.434984e+11,3.0,1.0,100.0,61.0,2021-09-17 18:23:46,2021-09-17 19:08:46,414086.0,2700.0

KeyError: 'Sınav Saati'

In [11]:
#deneme

exams_df['Giriş Zamanı'] = pd.to_datetime(exams_df['Giriş Zamanı'], format='%d/%m/%Y %H:%M:%S')
exams_df['Çıkış Zamanı'] = pd.to_datetime(exams_df['Çıkış Zamanı'], format='%d/%m/%Y %H:%M:%S')

exams_df['Giriş Zamanı']

0      2021-09-07 20:40:54
1      2021-09-09 21:20:08
2      2021-09-12 11:03:55
3      2021-09-13 14:03:34
4      2021-09-13 18:53:41
               ...
8300   2021-09-29 07:14:31
8301   2021-09-29 07:15:10
8302   2021-09-29 18:55:21
8303   2021-09-29 18:57:38
8304   2021-09-27 21:15:37
Name: Giriş Zamanı, Length: 8305, dtype: datetime64[ns]

In [12]:
# to drop the members who attempt gaming the system, I crate a deep copy of exams_df to exams_df_nongts.

exams_df_nongts = exams_df.copy(deep=True)

# create a new column for labeling and overlapping time

exams_df_nongts['Label'] = ""
exams_df_nongts['Overlap (secs.)'] = ""


# then we write the conditions for labeling the data who "Gaming the System"

for i in range(1,len(exams_df_nongts)):
    if exams_df_nongts['Üye'][i-1] == exams_df_nongts['Üye'][i]:
        if exams_df_nongts['Sınav'][i-1] == exams_df_nongts['Sınav'][i]:
            if exams_df_nongts['Konu'][i-1] == exams_df_nongts['Konu'][i]:
                if (exams_df_nongts['Çıkış Zamanı'][i-1] > exams_df_nongts['Giriş Zamanı'][i]) and (exams_df_nongts['Puan'][i-1] < exams_df_nongts['Puan'][i]) and (exams_df_nongts['GirişLog'][i-1] == exams_df_nongts['GirişLog'][i]):
                    exams_df_nongts['Label'][i] = "Gaming the System"
                    exams_df_nongts['Overlap (secs.)'][i] = (exams_df_nongts['Giriş Zamanı'][i] - exams_df_nongts['Çıkış Zamanı'][i-1]).total_seconds() * -1  # this is the overlapping time in seconds

C:\Users\Samsung\AppData\Local\Temp\ipykernel_6272\1861049980.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exams_df_nongts['Label'][i] = "Gaming the System"
C:\Users\Samsung\AppData\Local\Temp\ipykernel_6272\1861049980.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exams_df_nongts['Overlap (secs.)'][i] = (exams_df_nongts['Giriş Zamanı'][i] - exams_df_nongts['Çıkış Zamanı'][i-1]).total_seconds() * -1  # this is the overlapping time in seconds

In [13]:
#exam data without gaming the system incidents

exams_df_nongts=exams_df_nongts.loc[exams_df_nongts['Label'] != 'Gaming the System']

exams_df_nongts.sort_values(by=['Konu','Üye'])

exams_df_nongts

,Üye,Sınav,Konu,Sınav Türü,Doğru Sayısı,Yanlış Sayısı,Boş Sayısı,Puan,Giriş Zamanı,Çıkış Zamanı,Süre,GirişLog,Label,Overlap (secs.)
0,2910824,268222943622,8964,1,8,1,1,80,2021-09-07 20:40:54,2021-09-07 20:45:06,237,128004,,
1,2910824,501151045356,9535,1,9,0,1,90,2021-09-09 21:20:08,2021-09-09 21:24:25,241,182887,,
2,2910824,934072969211,9659,1,8,2,0,80,2021-09-12 11:03:55,2021-09-12 12:48:24,149,238434,,
3,2910824,934072969211,9659,1,9,1,0,90,2021-09-13 14:03:34,2021-09-13 14:14:50,659,273943,,
4,2910824,438484723,4421,1,4,6,0,40,2021-09-13 18:53:41,2021-10-07 19:32:12,115,285795,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8299,2428472503,45103129645,8271,1,4,1,0,80,2021-09-29 07:09:59,2021-09-29 07:14:40,254,827926,,
8301,2428472503,590286074810,9839,1,5,0,0,100,2021-09-29 07:15:10,2021-09-29 07:20:16,143,827926,,
8302,2428472503,120928860188,8892,1,10,0,0,100,2021-09-29 18:55:21,2021-09-29 18:56:32,45,850540,,
8303,2428472503,503968695758,8270,1,5,0,0,100,2021-09-29 18:57:38,2021-09-29 19:01:13,53,850540,,
8304,2429470368,937151774577,8736,2,12,7,1,60,2021-09-27 21:15:37,2021-09-27 21:31:34,932,786187,,

In [14]:
#investigate the data via pandasgui

show(exams_df_nongts)

PandasGUI INFO — pandasgui.gui — Opening PandasGUI

TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'int'
  move(self, int, int): argument 2 has unexpected type 'float'

Gaming the system yapanları drop et
sonra exam table üzerinden öğrencilerin başarılarını gözlemle

# exam table üzerinden ML işlemleri yap

In [15]:
df=exams_df_nongts

df

,Üye,Sınav,Konu,Sınav Türü,Doğru Sayısı,Yanlış Sayısı,Boş Sayısı,Puan,Giriş Zamanı,Çıkış Zamanı,Süre,GirişLog,Label,Overlap (secs.)
0,2910824,268222943622,8964,1,8,1,1,80,2021-09-07 20:40:54,2021-09-07 20:45:06,237,128004,,
1,2910824,501151045356,9535,1,9,0,1,90,2021-09-09 21:20:08,2021-09-09 21:24:25,241,182887,,
2,2910824,934072969211,9659,1,8,2,0,80,2021-09-12 11:03:55,2021-09-12 12:48:24,149,238434,,
3,2910824,934072969211,9659,1,9,1,0,90,2021-09-13 14:03:34,2021-09-13 14:14:50,659,273943,,
4,2910824,438484723,4421,1,4,6,0,40,2021-09-13 18:53:41,2021-10-07 19:32:12,115,285795,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8299,2428472503,45103129645,8271,1,4,1,0,80,2021-09-29 07:09:59,2021-09-29 07:14:40,254,827926,,
8301,2428472503,590286074810,9839,1,5,0,0,100,2021-09-29 07:15:10,2021-09-29 07:20:16,143,827926,,
8302,2428472503,120928860188,8892,1,10,0,0,100,2021-09-29 18:55:21,2021-09-29 18:56:32,45,850540,,
8303,2428472503,503968695758,8270,1,5,0,0,100,2021-09-29 18:57:38,2021-09-29 19:01:13,53,850540,,
8304,2429470368,937151774577,8736,2,12,7,1,60,2021-09-27 21:15:37,2021-09-27 21:31:34,932,786187,,

In [ ]:
#drop the unnecessary columns

df=df.drop(['GirişLog','Label','Overlap (secs.)'],axis=1)

In [ ]:
df

In [ ]:
#get Puan and Süre values and assign to x

x=df.iloc[:,[3,7]].values

In [ ]:
#finding optimal number of clusters using the elbow method  
import matplotlib.pyplot as mtp   

from sklearn.cluster import KMeans
wcss_list=[]

for i in range(1,11):
    kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
    kmeans.fit(x)
    wcss_list.append(kmeans.inertia_)
mtp.plot(range(1,11),wcss_list)
mtp.title('The Elbow Method')
mtp.xlabel('Number of clusters')
mtp.ylabel('WCSS')
mtp.show()

In [ ]:
#training the K-means model on a dataset  

kmeans=KMeans(n_clusters=3,init='k-means++',random_state=42)
y_predict=kmeans.fit_predict(x)

In [ ]:
#visulaizing the clusters

mtp.scatter(x[y_predict == 0, 0], x[y_predict == 0, 1], s = 100, c = 'blue', label = 'Cluster 1') #for first cluster  
mtp.scatter(x[y_predict == 1, 0], x[y_predict == 1, 1], s = 100, c = 'green', label = 'Cluster 2') #for second cluster  
mtp.scatter(x[y_predict== 2, 0], x[y_predict == 2, 1], s = 100, c = 'red', label = 'Cluster 3') #for third cluster  
mtp.scatter(x[y_predict == 3, 0], x[y_predict == 3, 1], s = 100, c = 'cyan', label = 'Cluster 4') #for fourth cluster  
#mtp.scatter(x[y_predict == 4, 0], x[y_predict == 4, 1], s = 100, c = 'magenta', label = 'Cluster 5') #for fifth cluster
#mtp.scatter(x[y_predict == 5, 0], x[y_predict == 5, 1], s = 100, c = 'purple', label = 'Cluster 6') #for sixth cluster    
mtp.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s = 300, c = 'yellow', label = 'Centroid')   
mtp.title('Clusters of students')  
mtp.xlabel('Puan')  
mtp.ylabel('Süre')  
mtp.legend()  
mtp.show()